import {test} from 'node:test';import assert from 'node:assert/strict';import {approvalDatabase} from './fixtures/approval-database.ts';
const delivery=await import('../supabase/functions/_shared/approval-delivery.ts').catch(()=>null);
async function fixture(){const f=await approvalDatabase();await f.enable();const e=await f.event(),pending=await f.rpc('agent:apply',{id:e.id,action:f.inspection(e).operation}),r=(await f.db.query<any>('select private.finance_approval_json($1) r',[pending.request_id])).rows[0].r;await f.db.exec('delete from private.outbox where approval_notice_id is null');const calls:any[]=[];let mode='ok';
 const io={rpc:f.rpc,botUsername:'synthetic_bot',telegram:async(method:string,body:any)=>{calls.push({method,body});if(method==='getChatMemberCount')return 3;if(method==='getChatMember'){if(mode==='member_error')throw Error('temporary');return {status:mode==='left'?'left':'member'};}if(method==='sendMessage'&&body.chat_id==='202'&&['blocked','timeout'].includes(mode))throw Object.assign(Error('transport'),{deliveryStatus:mode==='blocked'?'definitely_unavailable':'uncertain'});return {message_id:100+calls.length};}};
 async function send(){assert.ok(delivery);const item=await f.rpc('queue:outbox');assert.ok(item.id);await delivery.deliverApprovalNotice(item,io);return item;}
 return {...f,r,calls,io,send,setMode:(m:string)=>mode=m,notices:async()=>(await f.db.query<any>('select * from private.approval_notices order by id')).rows};}
test('initial plus two hourly rounds never becomes a fourth and downtime does not burst',async()=>{const f=await fixture();try{
 assert.equal((await f.notices()).length,1);await f.send();await f.elapse(59*60*1000);await f.rpc('approval:due');assert.equal((await f.notices()).length,1);await f.elapse(60*1000+5);await Promise.all([f.rpc('approval:due'),f.rpc('approval:due')]);assert.equal((await f.notices()).length,2);await f.send();await f.elapse(5*60*60*1000);await f.rpc('approval:due');assert.equal((await f.notices()).length,3);await f.send();await f.rpc('approval:due');await f.elapse(24*60*60*1000);await f.rpc('approval:due');assert.equal((await f.notices()).length,3);assert.equal(f.calls.filter(x=>x.method==='sendMessage').length,3);
 const body=f.calls.find(x=>x.method==='sendMessage').body;assert.equal(body.entities[0].type,'text_mention');assert.equal(body.entities[0].user.id,202);assert.equal(body.reply_markup.inline_keyboard[0].length,2);assert.ok(body.reply_markup.inline_keyboard[1][0].url.includes('start=confirmaciones'));
}finally{await f.db.close();}});
for(const mode of ['blocked','timeout'])test('private '+mode+(mode==='blocked'?' falls back within the same round':' has no fallback or resend'),async()=>{const f=await fixture();try{await f.send();await f.db.exec("insert into private.approval_private_chats(member_id,chat_id) values('202','202')");await f.elapse(3600001);await f.rpc('approval:due');f.setMode(mode);const item=await f.send();const sends=f.calls.filter(x=>x.method==='sendMessage');assert.equal(sends.length,mode==='blocked'?3:2);assert.equal(sends[1].body.chat_id,'202');assert.equal((await f.notices()).length,2);assert.equal((await f.notices())[1].state,mode==='blocked'?'sent':'uncertain');assert.equal((await f.rpc('approval:begin_notice',{outbox_id:item.id,token:item.token})).send,false);}finally{await f.db.close();}});
test('crash after begin consumes a round and does not send on lease recovery',async()=>{const f=await fixture();try{const item=await f.rpc('queue:outbox');assert.equal((await f.rpc('approval:begin_notice',{outbox_id:item.id,token:item.token})).send,true);await f.db.exec("update private.outbox set lease_until=now()-interval '1 second'");const next=await f.rpc('queue:outbox');await delivery!.deliverApprovalNotice(next,f.io);assert.equal(f.calls.filter(x=>x.method==='sendMessage').length,0);assert.equal((await f.notices())[0].state,'uncertain');await f.rpc('approval:due');assert.equal((await f.notices()).length,1);}finally{await f.db.close();}});
test('former members receive no notice and temporary verification does not consume round',async()=>{const f=await fixture();try{f.setMode('member_error');await assert.rejects(f.send(),/temporary/);assert.equal((await f.notices())[0].state,'queued');await f.db.exec("update private.outbox set lease_until=now()-interval '1 second'");f.setMode('left');await f.send();assert.equal(f.calls.filter(x=>x.method==='sendMessage').length,0);assert.equal((await f.notices())[0].state,'cancelled');await f.elapse(3600001);await f.rpc('approval:due');assert.equal((await f.notices()).length,1);}finally{await f.db.close();}});
for(const state of ['rejected','cancelled','superseded','expired','posted'])test('terminal '+state+' request sends no queued or later notice',async()=>{const f=await fixture();try{await f.db.query('update private.approval_requests set state=$1 where id=$2',[state,f.r.id]);await f.send();assert.equal(f.calls.filter(x=>x.method==='sendMessage').length,0);await f.elapse(3600001);await f.rpc('approval:due');assert.equal((await f.notices()).length,1);}finally{await f.db.close();}});
test('confirmation in flight leaves final state posted and cancels later sends',async()=>{const f=await fixture();try{const item=await f.rpc('queue:outbox'),begun=await f.rpc('approval:begin_notice',{outbox_id:item.id,token:item.token});const ev=await f.event('202','',{callback:'aconfirm:'+f.r.id+':'+f.r.revision});await f.rpc('approval:resolve',{id:ev.id,request_id:f.r.id,revision:f.r.revision,decision:'confirm'});await f.rpc('approval:notice_result',{notice_id:begun.notice_id,token:item.token,outcome:'sent',telegram_message_id:100});assert.equal((await f.db.query<any>('select state from private.approval_requests where id=$1',[f.r.id])).rows[0].state,'posted');await f.elapse(3600001);await f.rpc('approval:due');assert.equal((await f.notices()).length,1);}finally{await f.db.close();}});
